import { z } from "zod";

export const firmSchema = z.object({
  name: z.string().min(1),
  slug: z.string().min(1).optional(),
  description: z.string().optional().nullable(),
  longOverview: z.string().optional().nullable(),
  websiteUrl: z.string().optional().nullable(),
  affiliateUrl: z.string().optional().nullable(),
  discountCode: z.string().optional().nullable(),
  discountPercent: z.coerce.number().int().min(0).max(100).optional().nullable(),
  logoUrl: z.string().optional().nullable(),
  countryCode: z.string().optional().nullable(),
  ceoName: z.string().optional().nullable(),
  foundedAt: z.string().optional().nullable(),
  category: z.string().default("forex"),
  assetTypes: z.string().default("forex,crypto"),
  platforms: z.string().default(""),
  profitSplit: z.string().optional().nullable(),
  maxDrawdown: z.string().optional().nullable(),
  drawdownTypes: z.string().optional().nullable(),
  minFee: z.coerce.number().optional().nullable(),
  maxAllocation: z.string().optional().nullable(),
  startingPrice: z.string().optional().nullable(),
  payoutSpeed: z.string().optional().nullable(),
  pros: z.string().optional().nullable(),
  cons: z.string().optional().nullable(),
  rankOrder: z.coerce.number().int().default(999),
  isNew: z.boolean().default(false),
  featured: z.boolean().default(false),
  published: z.boolean().default(true),
  newsTrading: z.boolean().default(false),
  weekendHolding: z.boolean().default(false),
  expertAdvisors: z.boolean().default(false),
  copyTrading: z.boolean().default(false),
  noTimeLimit: z.boolean().default(false),
  consistencyRule: z.boolean().default(false),
  instantFunded: z.boolean().default(false),
  showInOffers: z.boolean().default(false),
  brandColor: z.string().optional().nullable(),
  legalName: z.string().optional().nullable(),
  headquarters: z.string().optional().nullable(),
  trustScore: z.coerce.number().int().min(0).max(100).optional().nullable(),
  verified: z.boolean().default(false),
  referralStats: z.string().optional().nullable(),
  incentiveText: z.string().optional().nullable(),
  challengeTypes: z.string().optional().nullable(),
  maxChallengeFee: z.coerce.number().optional().nullable(),
  profitTargetP1: z.string().optional().nullable(),
  profitTargetP2: z.string().optional().nullable(),
  payoutFrequency: z.string().optional().nullable(),
  brokerName: z.string().optional().nullable(),
  dailyDrawdown: z.string().optional().nullable(),
  minTradingDays: z.string().optional().nullable(),
  maxTradingDays: z.string().optional().nullable(),
  scalingPlan: z.string().optional().nullable(),
  swapFree: z.string().optional().nullable(),
  drawdownExplained: z.string().optional().nullable(),
  rulesDetail: z.string().optional().nullable(),
  payoutsDetail: z.string().optional().nullable(),
  faqJson: z.string().optional().nullable(),
  profileUpdatedAt: z.string().optional().nullable(),
});

export type FirmInput = z.infer<typeof firmSchema>;

export function firmInputToDb(data: FirmInput, slug: string) {
  return {
    name: data.name,
    slug,
    description: data.description || null,
    longOverview: data.longOverview || null,
    websiteUrl: data.websiteUrl || null,
    affiliateUrl: data.affiliateUrl || null,
    discountCode: data.discountCode || null,
    discountPercent: data.discountPercent ?? null,
    logoUrl: data.logoUrl || null,
    countryCode: data.countryCode?.toUpperCase() || null,
    ceoName: data.ceoName || null,
    foundedAt: data.foundedAt ? new Date(data.foundedAt) : null,
    category: data.category || "forex",
    assetTypes: data.assetTypes,
    platforms: data.platforms || "",
    profitSplit: data.profitSplit || null,
    maxDrawdown: data.maxDrawdown || null,
    drawdownTypes: data.drawdownTypes || null,
    minFee: data.minFee ?? null,
    maxAllocation: data.maxAllocation || null,
    startingPrice: data.startingPrice || null,
    payoutSpeed: data.payoutSpeed || null,
    pros: data.pros || null,
    cons: data.cons || null,
    rankOrder: data.rankOrder,
    isNew: data.isNew,
    featured: data.featured,
    published: data.published,
    newsTrading: data.newsTrading,
    weekendHolding: data.weekendHolding,
    expertAdvisors: data.expertAdvisors,
    copyTrading: data.copyTrading,
    noTimeLimit: data.noTimeLimit,
    consistencyRule: data.consistencyRule,
    instantFunded: data.instantFunded,
    showInOffers: data.showInOffers,
    brandColor: data.brandColor || null,
    legalName: data.legalName || null,
    headquarters: data.headquarters || null,
    trustScore: data.trustScore ?? null,
    verified: data.verified,
    referralStats: data.referralStats || null,
    incentiveText: data.incentiveText || null,
    challengeTypes: data.challengeTypes || null,
    maxChallengeFee: data.maxChallengeFee ?? null,
    profitTargetP1: data.profitTargetP1 || null,
    profitTargetP2: data.profitTargetP2 || null,
    payoutFrequency: data.payoutFrequency || null,
    brokerName: data.brokerName || null,
    dailyDrawdown: data.dailyDrawdown || null,
    minTradingDays: data.minTradingDays || null,
    maxTradingDays: data.maxTradingDays || null,
    scalingPlan: data.scalingPlan || null,
    swapFree: data.swapFree || null,
    drawdownExplained: data.drawdownExplained || null,
    rulesDetail: data.rulesDetail || null,
    payoutsDetail: data.payoutsDetail || null,
    faqJson: data.faqJson || null,
    profileUpdatedAt: data.profileUpdatedAt ? new Date(data.profileUpdatedAt) : null,
  };
}
