services:
  postgres:
    image: postgres:16-alpine
    container_name: prop-platform-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prop
      POSTGRES_PASSWORD: prop_local_dev
      POSTGRES_DB: prop_platform
    volumes:
      - prop_pg_data:/var/lib/postgresql/data

volumes:
  prop_pg_data:
